### ISSUE TITLE
WireGuard UI half a year out of date

### ISSUE THREAD

**Issue by dieser-niko** [hetznercloud/apps#102]
Version 0.4.0, released on Dec 2, 2022 is more than half an year old. It should be replaced by version 0.5.2, which was released on June 23.

Also, the default user is currently admin, which can't be easily changed. This should be changed in the install script so that I can use a different username.

**Comment by Kjarrigan** [comment]
Thanks for reporting. We'll have a look.

**Comment by MarcusWichelmann** [comment]
Just to let you know, we'll wait for https://github.com/ngoduykhanh/wireguard-ui/pull/427 to get released before updating the app to the latest version.

**Comment by MarcusWichelmann** [comment]
We released an update for our WireGuard app now.
It uses an own build of wireguard-ui v0.5.2 that includes some fixes that weren't merged upstream yet.

It's also possible to select a different username now.
