### ISSUE TITLE
docs: image collaboration-tools not available

### ISSUE THREAD

**Issue by rudolfbatke** [hetznercloud/apps#108]
Please update image in the example bellow with "collab-tools".

https://github.com/hetznercloud/apps/blob/5adb688631313a0e7433af09c6f30eae595c7293/apps/hetzner/collab-tools/README.md?plain=1#L32

**Comment by Kjarrigan** [comment]
Sorry for the late reply. You are correct this should be `collab-tools` and was also wrong in the hcloud section. This has been fixed and deployed to the docs https://docs.hetzner.com/cloud/apps/list/collaboration-tools
