### ISSUE TITLE
Do you accept new pull requests for new apps ? 

### ISSUE THREAD

**Issue by ricristian** [hetznercloud/apps#113]
### TL;DR

Hi, 

Any news regarding accepting new pull requests with new apps ? I would love to create 3 new pull requests for mysql, postgres and gitlab-runner ( without the gitlab instance just a standalone runner ) 

### Expected behavior

Adding multiple apps would be a great benefit for everybody, hetzner as company and we as consumers of the service.
Of course that I can create my own image using packer but not why share this with other peoples ? Collectively, a lot of time can be saved.

Cheers,

**Comment by Kjarrigan** [comment]
Hey @ricristian ,

unfortunately we currently do not accept pull requests for new apps. This might change in the future but is not planned at the moment.
