### ISSUE TITLE
What for I need GITHUB_SHA ?

### ISSUE THREAD

**Issue by denisgolius** [hetznercloud/apps#29]
Hello!

Can some one describe for what I need to generate `GITHUB_SHA` or where to find it?
For example DigitalOcean do not used it - see https://github.com/digitalocean/droplet-1-clicks/blob/master/docker-20-04/template.json

**Comment by Flipez** [comment]
Hi @denisgolius,

This variable is exposed by GitHub automatically (see [Documentation](https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables)) and we use it to trace a release to a specific commit.
