### ISSUE TITLE
jitsi cannot stream to youtube

### ISSUE THREAD

**Issue by mmmaxxxe** [hetznercloud/apps#36]
Hello,
it seems to me that jitsi cannot send streams to youtube. (option is disabled)

**Comment by Flipez** [comment]
Hi @mmmaxxxe 

I think you need a more advanced installation for that. I found a detailed guide [here](https://community.jitsi.org/t/how-to-to-setup-integrated-jitsi-and-jibri-for-dummies-my-comprehensive-tutorial-for-the-beginner/35718) which does cover a lot of steps. It seems like additionally to jitsi also a jibri instance is required which we currently do not support.
