### ISSUE TITLE
wireguard connects but no internet

### ISSUE THREAD

**Issue by sajjadintel** [hetznercloud/apps#64]
Hi,
I created a wireguard app using hetzner cloud. It connects but there is no internet!

**Comment by sajjadintel** [comment]
@androidacy-user Iran has blocked wireguard, so if it doesn't connect it's because of Iran firewall. I tried several wireguard installation.

**Comment by MarcusWichelmann** [comment]
@androidacy-user What was your issue with the nftables configuration? MTU/MSS issues maybe?
