### ISSUE TITLE
WireGuard README.md not in sync with docs.hetzner.com

### ISSUE THREAD

**Issue by wpdevelopment11** [hetznercloud/apps#77]
[WireGuard page](https://docs.hetzner.com/cloud/apps/list/wireguard) was built from the [old README.md](https://github.com/hetznercloud/apps/blob/1ba77d1e550eaf40043feef083dc307a892d7629/apps/hetzner/wireguard/README.md) (without video).
[Current README.md](https://github.com/hetznercloud/apps/blob/main/apps/hetzner/wireguard/README.md) contains a video tutorial.
WireGuard page should be updated. Same for German version.

**Comment by Kjarrigan** [comment]
Thanks for reporting @wpdevelopment11 . The sync has been fixed and the [WireGuard page](https://docs.hetzner.com/cloud/apps/list/wireguard/) now shows the latest version including the video.
