### ISSUE TITLE
Lots of issues

### ISSUE THREAD

**Issue by RinnDog** [hetznercloud/apps#78]
While this isn't a proper issue report, this pre-install has many bugs when it comes to making your site HTTPs using things like Cloudflare which causes issues with lots of plugins and themes.

**Comment by Kjarrigan** [comment]
Hey @RinnDog 

> While this isn't a proper issue report

I'll reopen this issue once it is a proper report. Which app/pre-install script are you referring to? Which version have you tried? What bugs did you encounter?

Besides it is not intended nor claimed that the One-Click-Apps are ready for every possible use-case.
