### ISSUE TITLE
cadvisor:latest doesn't provide arm support

### ISSUE THREAD

**Issue by th3noname** [hetznercloud/apps#98]
Apps like prometheus/grafana include the cadvisor image with latest tag. Sadly the cadvisor project is not updating the latest tag, so this image is two years old and doesnt include arm support (which landed in summer 2022, see https://github.com/google/cadvisor/pull/3141).

This causes the app not fully working on the new Hetzner CAX instances.

The version needs to be set to an actual Version since the cadvisor project is not going to change the tag (https://github.com/google/cadvisor/issues/2542).

**Comment by Kjarrigan** [comment]
Thanks for reporting. We'll have a look.

**Comment by Kjarrigan** [comment]
Sorry, I never have actually reported that we've fixed that. As you suggested we're using an actual tag now for cadvisor. Thanks again for reporting :slightly_smiling_face:
